// SPDX-License-Identifier: GPL-3.0-or-later

//! Raw FFI bindings to libchromadec, generated by bindgen from the public C
//! headers. Everything here is `unsafe` and mirrors the C API one-to-one; use
//! the `chromadec` crate for a safe, idiomatic interface.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(rustdoc::broken_intra_doc_links)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
